### ISSUE TITLE
What is the name of this vim colorscheme?

### ISSUE THREAD

**Issue by M0nenvoy** [Hammster/windows-terminal-shaders#13]
https://github.com/Hammster/windows-terminal-shaders/blob/main/.github/transparent-1.png

**Comment by Hammster** [comment]
Hey sorry for the very late response it's https://github.com/nikolvs/vim-sunbather  you can grab low color vim themes from here https://github.com/mcchrish/vim-no-color-collections or take a look on my vscode theme https://github.com/Hammster/bichromatic/tree/main
