### ISSUE TITLE
Not work for me - using Version: `1.12.3472.0`    

### ISSUE THREAD

**Issue by peymanmajidi** [Hammster/windows-terminal-shaders#16]
I've using latest version of Windows Terminal and WT Preview   
But shaders not work for me at all
![image](https://user-images.githubusercontent.com/24313930/151446766-e3063508-4243-4d67-8bc3-aa79ecef6404.png)

Version: `1.12.3472.0`    
Is there any extra trick which I don't know?

**Comment by oseughu** [comment]
Try adding the full path. In your case, this would be  something like "C:\\Users\\Peyman\\Path\\To\\crt.hlsl"

**Comment by Hammster** [comment]
This should work with a full path, I also tested if this works from non-primary hard drive, which it does. Feel free to drop a comment if this issue still exists and i will reopen it 👍
