### ISSUE TITLE
No CRT distortion

### ISSUE THREAD

**Issue by Psychlist1972** [Hammster/windows-terminal-shaders#3]
When I use this with the latest Terminal, I don't see any CRT distortion at all. Not sure if I missed a step, or if that is broken.

This is all that should be needed, AFAIK:

#define ENABLE_CURVE 1

Pete

**Comment by Psychlist1972** [comment]
This looks like it may be an issue with the latest Terminal not loading shaders at all.

**Comment by Hammster** [comment]
Correct, the next preview build that includes this commit will fix it https://github.com/microsoft/terminal/commit/77f181febd704d9c81dfbcf5d8c84ad92ed53523
