### ISSUE TITLE
How do I change the color?

### ISSUE THREAD

**Issue by Ewokkkkk** [Hammster/windows-terminal-shaders#7]
I have installed it, but I would like to change the default CRT to Green or Ember Monochrome.
How do I do that?

**Comment by Hammster** [comment]
You can change the settings in here, you need to set `ENABLE_TINT = 1` and set the color you want` #define TINT_COLOR float4(1, 0.7f, 0, 0) ` it's a RGBA float value which goes from 0 to 1 for each color channel :)

https://github.com/Hammster/windows-terminal-shaders/blob/5ad7801946169e586539d5fa76e5e2649f2d1b16/crt.hlsl#L12-L20

**Comment by Ewokkkkk** [comment]
I hadn't changed `ENABLE_TINT = 0`, so I changed it and it works.

Thank you for your answer and nice shedder :)
